# Generated by Django 4.1 on 2022-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_autor_editora_livro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={},
        ),
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="core.autor"),
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="autor",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
