# Generated by Django 4.1 on 2022-10-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_autor_options_livro_autores_alter_autor_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
    ]
