# Generated by Django 4.1 on 2022-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_autor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
